language: ruby
before_install:
  - gem install bundler
before_script:
  - rake db:migrate
script:
  - rake ci
rvm:
  - 2.4.2
  - 2.5.1
gemfile:
  - test/gemfiles/Gemfile.rails.5.2
  - test/gemfiles/Gemfile.rails.6.0
branches:
  only:
    - master
    - rails6
matrix:
  fast_finish: true
jobs:
  exclude:
  - rvm: 2.4.2
    gemfile: test/gemfiles/Gemfile.rails.6.0
