language: ruby
before_install:
  - gem install bundler
before_script:
  - rake db:migrate
script:
  - rake ci
rvm:
  - 2.7.4
gemfile:
  - test/gemfiles/Gemfile.rails.6.0
  - test/gemfiles/Gemfile.rails.6.1
branches:
  only:
    - master
    - rails6
jobs:
  fast_finish: true
