dist: xenial
services:
  - xvfb
addons:
  sources:
  - google-chrome
  apt:
    packages:
    - google-chrome-stable

language: ruby
rvm:
  - 2.7.4
gemfile:
  - test/gemfiles/Gemfile.rails.6.0
  - test/gemfiles/Gemfile.rails.6.1
branches:
  only:
    - master
    - rails6
jobs:
  fast_finish: true
